// Code generated by cobctl. This go file is generated automatically, DO NOT EDIT.

package scopeauth

import "github.com/cobinhood/mochi/types"

var scopeMap = map[string]map[string]map[string][]types.Scope{

	"enums": {
		"transaction_query_type": {
			"enum":    {},
			"comment": {},
		},
		"audit_committee_vote_type": {
			"enum": {},
		},
		"audit_committee_resolution": {
			"enum": {},
		},
		"audit_committee_motion_type": {
			"enum": {},
		},
		"aml_status": {
			"enum": {},
		},
		"aml_check_type": {
			"enum": {},
		},
		"bank_account_type": {
			"enum": {},
		},
		"monthly_expected_trade_amount": {
			"enum": {},
		},
		"kyc_status": {
			"enum":    {},
			"comment": {},
		},
		"fatca_tax_payer_id_kind": {
			"enum": {},
		},
		"fatca_tax_payer_kind": {
			"enum": {},
		},
		"exchange_rate_query_dominant": {
			"comment": {},
			"enum":    {},
		},
		"ledger_type": {
			"enum":    {},
			"comment": {},
		},
		"wallet_usage": {
			"enum":    {},
			"comment": {},
		},
		"wallet_type": {
			"enum":    {},
			"comment": {},
		},
		"order_side": {
			"enum":    {},
			"comment": {},
		},
		"order_type": {
			"enum":    {},
			"comment": {},
		},
		"order_state": {
			"enum":    {},
			"comment": {},
		},
		"order_source": {
			"enum": {},
		},
		"funding_type": {
			"enum": {},
		},
		"loan_state": {
			"enum": {},
		},
		"service": {
			"enum":    {},
			"comment": {},
		},
		"device": {
			"enum":    {},
			"comment": {},
		},
		"2FA": {
			"enum":    {},
			"comment": {},
		},
		"login": {
			"enum":    {},
			"comment": {},
		},
		"account_type": {
			"enum":    {},
			"comment": {},
		},
		"locale": {
			"enum":    {},
			"comment": {},
		},
		"scope": {
			"enum":    {},
			"comment": {},
		},
		"third_party_scope": {
			"enum":    {},
			"comment": {},
		},
		"identity": {
			"enum": {},
		},
		"ledger_action": {
			"enum":    {},
			"comment": {},
		},
		"generic_deposit_type": {
			"enum":    {},
			"comment": {},
		},
		"generic_withdrawal_type": {
			"enum":    {},
			"comment": {},
		},
		"tx_status": {
			"enum":    {},
			"comment": {},
		},
		"sys_msg_category": {
			"enum":    {},
			"comment": {},
		},
		"platform": {
			"enum":    {},
			"comment": {},
		},
		"revoke_device_authorization": {
			"enum":    {},
			"comment": {},
		},
		"currency_type": {
			"enum":    {},
			"comment": {},
		},
		"timeframe_type": {
			"enum":    {},
			"comment": {},
		},
		"reward_type": {
			"enum": {},
		},
		"fiat_deposit_status": {
			"enum": {},
		},
		"fiat_withdrawal_status": {
			"enum": {},
		},
		"fiat_deposit_type": {
			"enum": {},
		},
		"fiat_withdrawal_type": {
			"enum": {},
		},
		"iota_withdrawal_status": {
			"enum":    {},
			"comment": {},
		},
		"price_alert_status": {
			"enum":    {},
			"comment": {},
		},
		"broker_order_status": {
			"enum": {},
		},
		"epay_in_status": {
			"enum": {},
		},
		"payment_method_type": {
			"enum":    {},
			"comment": {},
		},
		"shop_payment_type": {
			"enum": {},
		},
		"shop_item_type": {
			"enum": {},
		},
		"oauth2_token_type": {
			"enum": {},
		},
		"cob_point_constant_type": {
			"enum":    {},
			"comment": {},
		},
		"feature_table_type": {
			"enum": {},
		},
		"feature_table_action": {
			"enum": {},
		},
		"financial_product_type": {
			"enum": {},
		},
		"financial_product_provider": {
			"enum": {},
		},
		"financial_product_state": {
			"enum": {},
		},
		"funds_raising_project_type": {
			"enum": {},
		},
		"suspicious_transaction_record_investigation_status": {
			"enum": {},
		},
		"suspicious_transaction_rule": {
			"enum": {},
		},
		"coin_offering_state": {
			"enum": {},
		},
		"coin_offering_cap_type": {
			"enum": {},
		},
		"coin_offering_bonus_type": {
			"enum": {},
		},
		"quotation_query_type": {
			"enum": {},
		},
	},

	"types": {
		"custom_query_limit": {
			"type":    {},
			"comment": {},
		},
		"custom_query_page": {
			"type":    {},
			"comment": {},
		},
	},

	"objects": {
		"kyc_residence_information": {
			"type":                 {},
			"additionalProperties": {},
			"properties":           {},
		},
		"kyc_phone_number": {
			"type":                 {},
			"additionalProperties": {},
			"properties":           {},
		},
		"fatca_model": {
			"type":                 {},
			"additionalProperties": {},
			"properties":           {},
		},
		"2FA": {
			"type":                 {},
			"additionalProperties": {},
			"properties":           {},
		},
		"aml_model": {
			"type":                 {},
			"additionalProperties": {},
			"properties":           {},
		},
		"kyc_basic_information": {
			"type":                 {},
			"additionalProperties": {},
			"properties":           {},
		},
		"kyc_source_of_funds": {
			"type":                 {},
			"additionalProperties": {},
			"properties":           {},
		},
		"kyc_proof_of_identity": {
			"type":                 {},
			"additionalProperties": {},
			"properties":           {},
		},
		"api_token_model": {
			"type":                 {},
			"required":             {},
			"additionalProperties": {},
			"properties":           {},
		},
		"order": {
			"type":                 {},
			"required":             {},
			"additionalProperties": {},
			"properties":           {},
		},
		"position": {
			"type":                 {},
			"required":             {},
			"additionalProperties": {},
			"properties":           {},
		},
		"coin_source_type": {
			"type":                 {},
			"required":             {},
			"additionalProperties": {},
			"properties":           {},
		},
		"currency": {
			"type":                 {},
			"required":             {},
			"additionalProperties": {},
			"properties":           {},
		},
		"full_currency_type": {
			"type":                 {},
			"required":             {},
			"additionalProperties": {},
			"properties":           {},
		},
		"trade_statistics": {
			"type":                 {},
			"required":             {},
			"additionalProperties": {},
			"properties":           {},
		},
		"trading_pair": {
			"type":                 {},
			"required":             {},
			"additionalProperties": {},
			"properties":           {},
		},
		"full_trading_pair_object": {
			"type":                 {},
			"required":             {},
			"additionalProperties": {},
			"properties":           {},
		},
		"trade": {
			"type":                 {},
			"required":             {},
			"additionalProperties": {},
			"properties":           {},
		},
		"ticker": {
			"type":                 {},
			"required":             {},
			"additionalProperties": {},
			"properties":           {},
		},
		"general_ticker": {
			"type":                 {},
			"required":             {},
			"additionalProperties": {},
			"properties":           {},
		},
		"currency_intro": {
			"type":              {},
			"required":          {},
			"properties":        {},
			"patternProperties": {},
		},
		"candle": {
			"type":                 {},
			"required":             {},
			"additionalProperties": {},
			"properties":           {},
			"cob_factor_mapping":   {},
		},
		"redemption": {
			"type":                 {},
			"required":             {},
			"additionalProperties": {},
			"properties":           {},
		},
		"leaderboard": {
			"type":                 {},
			"required":             {},
			"additionalProperties": {},
			"properties":           {},
		},
		"scoreboard": {
			"type":                 {},
			"required":             {},
			"additionalProperties": {},
			"properties":           {},
		},
		"slotmachine_token": {
			"type":                 {},
			"required":             {},
			"additionalProperties": {},
			"properties":           {},
		},
		"slotmachine_reward": {
			"type":                 {},
			"required":             {},
			"additionalProperties": {},
			"properties":           {},
		},
		"balance": {
			"type":       {},
			"required":   {},
			"properties": {},
		},
		"iota_withdrawal": {
			"type":       {},
			"properties": {},
		},
		"iota_transaction": {
			"type":       {},
			"properties": {},
		},
		"generic_deposit": {
			"type":                 {},
			"required":             {},
			"additionalProperties": {},
			"properties":           {},
		},
		"generic_withdrawal": {
			"type":                 {},
			"required":             {},
			"additionalProperties": {},
			"properties":           {},
		},
		"deposit": {
			"type":       {},
			"required":   {},
			"properties": {},
		},
		"withdrawal": {
			"type":       {},
			"required":   {},
			"properties": {},
		},
		"ledger": {
			"type":       {},
			"required":   {},
			"properties": {},
		},
		"deposit_address": {
			"type":                 {},
			"additionalProperties": {},
			"required":             {},
			"properties":           {},
		},
		"withdrawal_address": {
			"type":                 {},
			"additionalProperties": {},
			"required":             {},
			"properties":           {},
		},
		"client": {
			"type":       {},
			"properties": {},
		},
		"kyc": {
			"type":       {},
			"properties": {},
		},
		"device_authorization": {
			"type":                 {},
			"additionalProperties": {},
			"required":             {},
			"properties":           {},
		},
		"fiat_deposit": {
			"type":       {},
			"properties": {},
		},
		"fiat_withdrawal": {
			"type":       {},
			"properties": {},
		},
		"epay_deposit": {
			"type":                 {},
			"additionalProperties": {},
			"properties":           {},
		},
		"funding": {
			"type":                 {},
			"required":             {},
			"additionalProperties": {},
			"properties":           {},
		},
		"loan": {
			"type":                 {},
			"required":             {},
			"additionalProperties": {},
			"properties":           {},
		},
		"auto_offering_type": {
			"enum":    {},
			"comment": {},
		},
		"auto_offering": {
			"type":                 {},
			"required":             {},
			"additionalProperties": {},
			"properties":           {},
		},
		"price_alert": {
			"type":       {},
			"required":   {},
			"properties": {},
		},
		"payment_method": {
			"type":       {},
			"required":   {},
			"properties": {},
		},
		"broker_order": {
			"type":                 {},
			"required":             {},
			"additionalProperties": {},
			"properties":           {},
		},
		"exchange_rate": {
			"type":                 {},
			"required":             {},
			"additionalProperties": {},
			"properties":           {},
		},
		"blacklist": {
			"type":                 {},
			"additionalProperties": {},
			"properties":           {},
		},
		"funds_raising_project": {
			"type":                 {},
			"required":             {},
			"additionalProperties": {},
			"properties":           {},
		},
		"funds_raising_record": {
			"type":                 {},
			"required":             {},
			"additionalProperties": {},
			"properties":           {},
		},
		"financial_product_report": {
			"type":                 {},
			"required":             {},
			"additionalProperties": {},
			"properties":           {},
		},
		"financial_product_info": {
			"type":                 {},
			"required":             {},
			"additionalProperties": {},
			"properties":           {},
		},
		"financial_product": {
			"type":                 {},
			"required":             {},
			"additionalProperties": {},
			"properties":           {},
		},
		"coin_offering_lock_rate": {
			"type":                 {},
			"required":             {},
			"additionalProperties": {},
			"properties":           {},
		},
		"coin_offering_tier_bonus": {
			"type":       {},
			"required":   {},
			"properties": {},
		},
		"coin_offering_period_bonus": {
			"type":       {},
			"required":   {},
			"properties": {},
		},
		"coin_offering_point_bonus": {
			"type":       {},
			"required":   {},
			"properties": {},
		},
		"coin_offering_rating": {
			"type":       {},
			"required":   {},
			"properties": {},
		},
		"coin_offering_info": {
			"type":                 {},
			"required":             {},
			"additionalProperties": {},
			"properties":           {},
		},
		"coin_offering": {
			"type":                 {},
			"required":             {},
			"additionalProperties": {},
			"properties":           {},
		},
	},

	"fieldsets": {
		"onesignal_language": {
			"pt":      {},
			"tr":      {},
			"de":      {},
			"zh-Hant": {},
			"es":      {},
			"ja":      {},
			"fr":      {},
			"nl":      {},
			"ru":      {},
			"zh-Hans": {},
			"ko":      {},
			"en":      {},
			"it":      {},
		},
		"aml_investigating": {
			"source_of_funds":                  {},
			"proof_of_source_of_funds_file_id": {},
			"monthly_expected_trade_amount":    {},
			"note":                             {},
			"contact_date":                     {},
			"contact_way":                      {},
		},
		"custom_query_request": {
			"limit": {},
			"page":  {},
		},
		"custom_query_pagination": {
			"limit":       {},
			"page":        {},
			"total_page":  {},
			"total_count": {},
		},
	},

	"api-cobx": {
		"/alive": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/ready": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/ws/common/common": {
			"WS": {
				types.ScopePublic,
			},
		},
		"/ws/common/ping-pong": {
			"WS": {
				types.ScopePublic,
			},
		},
		"/ws/common/subscribe": {
			"WS": {
				types.ScopePublic,
			},
		},
		"/ws/common/unsubscribe": {
			"WS": {
				types.ScopePublic,
			},
		},
		"/ws/common/errorcode": {
			"WS": {
				types.ScopePublic,
			},
		},
		"/ws/v2/order": {
			"WS": {
				types.ScopePublic,
			},
		},
		"/ws/v2/order_limit": {
			"WS": {
				types.ScopePublic,
			},
		},
		"/ws/v2/order_market": {
			"WS": {
				types.ScopePublic,
			},
		},
		"/ws/v2/order_stop": {
			"WS": {
				types.ScopePublic,
			},
		},
		"/ws/v2/order_limit_stop": {
			"WS": {
				types.ScopePublic,
			},
		},
		"/ws/v2/orderbook": {
			"WS": {
				types.ScopePublic,
			},
		},
		"/ws/v2/repl_orderbook/subscribe": {
			"WS": {
				types.ScopePublic,
			},
		},
		"/ws/v2/trade": {
			"WS": {
				types.ScopePublic,
			},
		},
		"/ws/v2/ticker": {
			"WS": {
				types.ScopePublic,
			},
		},
		"/ws/v2/candle": {
			"WS": {
				types.ScopePublic,
			},
		},
		"/ws/v2/loan": {
			"WS": {
				types.ScopePublic,
			},
		},
		"/ws/v2/loan-update": {
			"WS": {
				types.ScopePublic,
			},
		},
		"/ws/v2/funding": {
			"WS": {
				types.ScopePublic,
			},
		},
		"/ws/v2/fundingbook": {
			"WS": {
				types.ScopePublic,
			},
		},
		"/ws/v2/repl_fundingbook/subscribe": {
			"WS": {
				types.ScopePublic,
			},
		},
		"/ws/v2/loan-ticker": {
			"WS": {
				types.ScopePublic,
			},
		},
		"/ws/v2/balance-update": {
			"WS": {
				types.ScopePublic,
			},
		},
		"/ws/v2/position-update": {
			"WS": {
				types.ScopePublic,
			},
		},
		"/v1/system/version": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/system/time": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/system/info": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/system/messages": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/system/messages/:message_id": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/account/device": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/register": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/resend_email_verification": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/confirm_email_verification": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/check_email_verification": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/login": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/confirm_device_verification": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/check_device_verification": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/resend_device_verification": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/forgot_password": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/reset_password": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/change_password": {
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/account/enable_two_factor_authentication": {
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/account/verify_two_factor_authentication": {
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/account/confirm_enable_two_factor_authentication": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/disable_two_factor_authentication": {
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/account/confirm_disable_two_factor_authentication": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/change_email": {
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/account/confirm_change_email": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/delete_account": {
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/account/confirm_delete_account": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/ephemeral_picture": {
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/account/disable_two_factor_authentication_picture": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/request_disable_two_factor_authentication": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/confirm_request_disable_two_factor_authentication": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/confirm_two_factor_authentication": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/refresh_token": {
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/account/device_authorizations": {
			"GET": {
				types.ScopeExchangeAccountRead,
			},
		},
		"/v1/account/device_authorizations/:device_authorization_id": {
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/account/check_eosio_account_duplicated": {
			"GET": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/account/get_eos_required_amount": {
			"GET": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/account/create_eos_account": {
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/user/info": {
			"GET": {
				types.ScopeExchangeAccountRead,
			},
		},
		"/v1/user/vip_info": {
			"GET": {
				types.ScopeExchangeAccountRead,
			},
		},
		"/v1/user/api_token": {
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/user/api_token/:api_token_id/revoke": {
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/user/api_token/get_my_api_tokens": {
			"GET": {
				types.ScopeExchangeAccountRead,
			},
		},
		"/v1/user/api_token/get_my_available_scopes": {
			"GET": {
				types.ScopeExchangeAccountRead,
			},
		},
		"/v1/user/oauth2_tokens": {
			"GET": {
				types.ScopeExchangeAccountRead,
			},
		},
		"/v1/user/oauth2_tokens/revoke": {
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/user/preferences": {
			"GET": {
				types.ScopeExchangeAccountRead,
			},
			"PUT": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/user/price_alerts": {
			"GET": {
				types.ScopeExchangeAccountRead,
			},
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/user/price_alerts/:id": {
			"GET": {
				types.ScopeExchangeAccountRead,
			},
			"PUT": {
				types.ScopeExchangeAccountWrite,
			},
			"DELETE": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/user/cob_points": {
			"GET": {
				types.ScopeExchangeAccountRead,
			},
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/user/cob_point_ledgers": {
			"GET": {
				types.ScopeExchangeAccountRead,
			},
		},
		"/v1/user/points": {
			"GET": {
				types.ScopeExchangeAccountRead,
			},
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/user/points/:currency_id": {
			"GET": {
				types.ScopeExchangeAccountRead,
			},
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/user/reward_points": {
			"GET": {
				types.ScopeExchangeAccountRead,
			},
		},
		"/v1/user/feature_list": {
			"GET": {
				types.ScopeExchangeAccountRead,
			},
		},
		"/v1/market/currencies": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/quote_currencies": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/get_all_currency_intro": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/currency_intro/:currency_id": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/trading_pairs": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/stats": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/trades/:trading_pair_id": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/trades_history/:trading_pair_id": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/orderbooks/:trading_pair_id": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/orderbook/precisions/:trading_pair_id": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/fundingbooks/:currency_id": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/fundingbook/precisions/:currency_id": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/tickers": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/tickers/:trading_pair_id": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/loan_tickers": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/loan_tickers/:currency_id": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/exchange_rates/:currency_id": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/explorers": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/info": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/kyc/id_types": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/kyc/tiers": {
			"GET": {
				types.ScopeExchangeKYCRead,
			},
		},
		"/v1/kyc/tiers/:tier_level": {
			"GET": {
				types.ScopeExchangeKYCRead,
			},
			"PUT": {
				types.ScopeExchangeKYCWrite,
			},
		},
		"/v1/kyc/phone_number": {
			"POST": {
				types.ScopeExchangeKYCWrite,
			},
		},
		"/v1/kyc/ephemeral_picture": {
			"POST": {
				types.ScopeExchangeKYCWrite,
			},
		},
		"/v1/kyc/pictures/:picture_id": {
			"GET": {
				types.ScopeExchangeKYCRead,
			},
		},
		"/v1/trading/check_order": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/trading/orders": {
			"GET": {
				types.ScopeExchangeTradeRead,
			},
			"POST": {
				types.ScopeExchangeTradeWrite,
			},
		},
		"/v1/trading/orders/:order_id": {
			"GET": {
				types.ScopeExchangeTradeRead,
			},
			"DELETE": {
				types.ScopeExchangeTradeWrite,
			},
			"PUT": {
				types.ScopeExchangeTradeWrite,
			},
		},
		"/v1/trading/order_batch": {
			"POST": {
				types.ScopeExchangeTradeWrite,
			},
			"DELETE": {
				types.ScopeExchangeTradeWrite,
			},
		},
		"/v1/trading/orders/:order_id/trades": {
			"GET": {
				types.ScopeExchangeTradeRead,
			},
		},
		"/v1/trading/order_history": {
			"GET": {
				types.ScopeExchangeTradeRead,
			},
		},
		"/v1/trading/trades/:trade_id": {
			"GET": {
				types.ScopeExchangeTradeRead,
			},
		},
		"/v1/trading/trades": {
			"GET": {
				types.ScopeExchangeTradeRead,
			},
		},
		"/v1/trading/volume": {
			"GET": {
				types.ScopeExchangeTradeRead,
			},
		},
		"/v1/trading/positions": {
			"GET": {
				types.ScopeExchangeMarginTradeRead,
			},
		},
		"/v1/trading/positions/:trading_pair_id": {
			"GET": {
				types.ScopeExchangeMarginTradeRead,
			},
			"DELETE": {
				types.ScopeExchangeMarginTradeWrite,
			},
			"PATCH": {
				types.ScopeExchangeMarginTradeWrite,
			},
		},
		"/v1/trading/positions/:trading_pair_id/claimable_size": {
			"GET": {
				types.ScopeExchangeMarginTradeRead,
			},
		},
		"/v1/trading/quote": {
			"GET": {
				types.ScopeExchangeTradeRead,
			},
		},
		"/v1/trading/public/quote": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/trading/broker_orders": {
			"GET": {
				types.ScopeExchangeTradeRead,
			},
			"POST": {
				types.ScopeExchangeTradeWrite,
			},
		},
		"/v1/trading/broker_orders/:broker_order_id": {
			"GET": {
				types.ScopeExchangeTradeRead,
			},
			"PUT": {
				types.ScopeExchangeTradeWrite,
			},
			"DELETE": {
				types.ScopeExchangeTradeWrite,
			},
		},
		"/v1/trading/payment_methods": {
			"GET": {
				types.ScopeExchangeTradeRead,
			},
		},
		"/v1/trading/callback/epay/:broker_order_id": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/trading/callbacks/:type": {
			"GET": {
				types.ScopePublic,
			},
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/chart/candles/:trading_pair_id": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/wallet/balances": {
			"GET": {
				types.ScopeExchangeLedgerRead,
			},
		},
		"/v1/wallet/withdrawal_frozen": {
			"GET": {
				types.ScopeExchangeCryptoWithdrawal,
			},
		},
		"/v1/wallet/withdrawals/:withdrawal_id": {
			"GET": {
				types.ScopeExchangeLedgerRead,
			},
			"DELETE": {
				types.ScopeExchangeCryptoWithdrawal,
			},
		},
		"/v1/wallet/withdrawals": {
			"GET": {
				types.ScopeExchangeLedgerRead,
			},
			"POST": {
				types.ScopeExchangeCryptoWithdrawal,
			},
		},
		"/v1/wallet/withdrawals/fee": {
			"POST": {
				types.ScopeExchangeCryptoWithdrawal,
			},
		},
		"/v1/wallet/limits/withdrawal": {
			"GET": {
				types.ScopeExchangeLedgerRead,
			},
		},
		"/v1/wallet/deposits/:deposit_id": {
			"GET": {
				types.ScopeExchangeLedgerRead,
			},
		},
		"/v1/wallet/deposits": {
			"GET": {
				types.ScopeExchangeLedgerRead,
			},
		},
		"/v1/wallet/ledger": {
			"GET": {
				types.ScopeExchangeLedgerRead,
			},
		},
		"/v1/wallet/transfer": {
			"POST": {
				types.ScopeExchangeWalletTransfer,
			},
		},
		"/v1/wallet/generic_deposits": {
			"GET": {
				types.ScopeExchangeLedgerRead,
			},
		},
		"/v1/wallet/generic_deposits/:generic_deposit_id": {
			"GET": {
				types.ScopeExchangeLedgerRead,
			},
		},
		"/v1/wallet/generic_withdrawals": {
			"GET": {
				types.ScopeExchangeLedgerRead,
			},
		},
		"/v1/wallet/generic_withdrawals/:generic_withdrawal_id": {
			"GET": {
				types.ScopeExchangeLedgerRead,
			},
			"DELETE": {
				types.ScopeExchangeCryptoWithdrawal,
			},
		},
		"/v1/wallet/csv/ledgers": {
			"GET": {
				types.ScopeExchangeLedgerRead,
			},
		},
		"/v1/wallet/deposit_addresses": {
			"GET": {
				types.ScopeExchangeLedgerRead,
			},
			"POST": {
				types.ScopeExchangeCryptoWithdrawal,
			},
		},
		"/v1/wallet/deposit_addresses/iota": {
			"GET": {
				types.ScopeExchangeCryptoWithdrawal,
			},
			"POST": {
				types.ScopeExchangeCryptoWithdrawal,
			},
		},
		"/v1/wallet/withdrawal_addresses": {
			"GET": {
				types.ScopeExchangeLedgerRead,
			},
			"POST": {
				types.ScopeExchangeCryptoWithdrawal,
			},
		},
		"/v1/wallet/withdrawal_addresses/:wallet_id": {
			"DELETE": {
				types.ScopeExchangeCryptoWithdrawal,
			},
		},
		"/v1/wallet/confirm_add_withdrawal_wallet": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/wallet/confirm_withdrawal": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/fiat/limits/:currency_id": {
			"GET": {
				types.ScopeExchangeLedgerRead,
			},
		},
		"/v1/fiat/deposits": {
			"GET": {
				types.ScopeExchangeFiatDeposit,
			},
		},
		"/v1/fiat/deposits/:deposits_id": {
			"GET": {
				types.ScopeExchangeFiatDeposit,
			},
		},
		"/v1/fiat/withdrawals": {
			"GET": {
				types.ScopeExchangeFiatWithdrawal,
			},
			"POST": {
				types.ScopeExchangeFiatWithdrawal,
			},
		},
		"/v1/fiat/confirm_withdrawals": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/fiat/withdrawals/:withdrawal_id": {
			"GET": {
				types.ScopeExchangeFiatWithdrawal,
			},
			"DELETE": {
				types.ScopeExchangeFiatWithdrawal,
			},
		},
		"/v1/fiat/epay/withdrawals": {
			"POST": {
				types.ScopeExchangeFiatWithdrawal,
			},
		},
		"/v1/fiat/epay/deposit_callback/:deposit_id": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/fiat/epay/deposits": {
			"POST": {
				types.ScopeExchangeFiatDeposit,
			},
		},
		"/v1/fiat/epay/confirm_withdrawals": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/fiat/epay/redirect": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/fiat/kgi/account/propose": {
			"GET": {
				types.ScopeExchangeAccountWrite,
			},
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/campaign/slot_machine/play": {
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/campaign/slot_machine/wish": {
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/campaign/slot_machine/tokens": {
			"GET": {
				types.ScopeExchangeAccountRead,
			},
		},
		"/v1/campaign/slot_machine/rewards": {
			"GET": {
				types.ScopeExchangeAccountRead,
			},
		},
		"/v1/campaign/my_referee_count": {
			"GET": {
				types.ScopeExchangeAccountRead,
			},
		},
		"/v1/campaign/check_referrer/:referrer_id": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/campaign/get_user_sba_bonus": {
			"GET": {
				types.ScopeExchangeAccountRead,
			},
		},
		"/v1/campaign/redeem_user_sba_bonus": {
			"GET": {
				types.ScopeExchangeAccountRead,
			},
			"POST": {
				types.ScopeExchangeAccountRead,
			},
		},
		"/v1/campaign/get_all_end_point": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/campaign/events/:campaign_name/:component_name": {
			"GET": {
				types.ScopePublic,
			},
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/campaign/cob_factor_mapping": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/campaign/cob_factor": {
			"GET": {
				types.ScopeExchangeLedgerRead,
				types.ScopeExchangeAccountRead,
			},
		},
		"/v1/campaign/cob_factor_mapping_v2": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/campaign/cob_factor_v2": {
			"GET": {
				types.ScopeExchangeLedgerRead,
				types.ScopeExchangeAccountRead,
			},
		},
		"/v1/campaign/shop/items": {
			"GET": {
				types.ScopeExchangeAccountRead,
			},
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/campaign/shop/items/:item_id": {
			"GET": {
				types.ScopeExchangeAccountRead,
			},
		},
		"/v1/campaign/manual_review_submit/:event_name/:submit_id/:picture_id": {
			"GET": {
				types.ScopeExchangeAccountRead,
			},
		},
		"/v1/oauth2/info": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/oauth2/authorize": {
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/oauth2/token": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/oauth2/clients": {
			"GET": {
				types.ScopeExchangeOAuth2ClientRead,
			},
		},
		"/v1/oauth2/clients/:client_id/secret": {
			"GET": {
				types.ScopeExchangeOAuth2ClientRead,
			},
		},
		"/v1/oauth2/clients/:client_id/disable": {
			"POST": {
				types.ScopeExchangeOAuth2ClientWrite,
			},
		},
		"/v1/oauth2/resources/userinfo": {
			"GET": {
				types.ScopeThirdPartyAccountRead,
			},
		},
		"/v1/oauth2/clients/:client_id/extensions/kyc_project/stats": {
			"GET": {
				types.ScopeExchangeOAuth2ClientRead,
			},
		},
		"/v1/oauth2/clients/:client_id/extensions/kyc_project/notes": {
			"GET": {
				types.ScopeExchangeOAuth2ClientRead,
			},
		},
		"/v1/oauth2/resources/kyc_tiers": {
			"GET": {
				types.ScopeThirdPartyKYCRead,
			},
		},
		"/v1/oauth2/resources/internal_withdrawal_to_client_owner": {
			"POST": {
				types.ScopeThirdPartyInternalWithdraw,
			},
		},
		"/v1/oauth2/resources/kyc_project": {
			"GET": {
				types.ScopeThirdPartyKYCProjectRead,
			},
		},
		"/v1/oauth2/resources/kyc_project/signup": {
			"POST": {
				types.ScopeThirdPartyKYCProjectWrite,
			},
		},
		"/v1/oauth2/resources/kyc_project/leave": {
			"POST": {
				types.ScopeThirdPartyKYCProjectWrite,
			},
		},
		"/v1/oauth2/resources/kyc_project/notes": {
			"PUT": {
				types.ScopeThirdPartyKYCProjectWrite,
			},
		},
		"/v1/funding/fundings": {
			"GET": {
				types.ScopeExchangeFundingRead,
			},
			"POST": {
				types.ScopeExchangeFundingWrite,
			},
		},
		"/v1/funding/flash_return_rate/:currency_id": {
			"GET": {
				types.ScopeExchangeFundingRead,
			},
		},
		"/v1/funding/fundings/:funding_id": {
			"PUT": {
				types.ScopeExchangeFundingWrite,
			},
			"DELETE": {
				types.ScopeExchangeFundingWrite,
			},
		},
		"/v1/funding/funding_history": {
			"GET": {
				types.ScopeExchangeFundingRead,
			},
		},
		"/v1/funding/loans": {
			"GET": {
				types.ScopeExchangeFundingRead,
			},
		},
		"/v1/funding/loans/:loan_id": {
			"GET": {
				types.ScopeExchangeFundingRead,
			},
			"DELETE": {
				types.ScopeExchangeFundingWrite,
			},
		},
		"/v1/funding/auto_offerings": {
			"GET": {
				types.ScopeExchangeFundingRead,
			},
			"POST": {
				types.ScopeExchangeFundingWrite,
			},
		},
		"/v1/funding/auto_offerings/:currency_id": {
			"GET": {
				types.ScopeExchangeFundingRead,
			},
			"DELETE": {
				types.ScopeExchangeFundingWrite,
			},
		},
		"/v1/funds_raising/financial_products": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/funds_raising/closed_financial_products": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/funds_raising/financial_products/:id": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/funds_raising/financial_products/:id/invest": {
			"GET": {
				types.ScopeExchangeFundsRaising,
			},
			"POST": {
				types.ScopeExchangeFundsRaising,
			},
		},
		"/v1/funds_raising/financial_products/:id/return": {
			"POST": {
				types.ScopeExchangeFundsRaising,
			},
		},
		"/v1/funds_raising/coin_offerings": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/funds_raising/coin_offerings/:id": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/funds_raising/coin_offering_invests": {
			"GET": {
				types.ScopeExchangeFundsRaising,
			},
		},
		"/v1/funds_raising/coin_offerings/:id/invest": {
			"GET": {
				types.ScopeExchangeFundsRaising,
			},
			"POST": {
				types.ScopeExchangeFundsRaising,
			},
		},
		"/v1/funds_raising/coin_offerings/:id/refer": {
			"GET": {
				types.ScopeExchangeFundsRaising,
			},
		},
		"/v1/funds_raising/funds_raising_projects/:id/claim": {
			"POST": {
				types.ScopeExchangeFundsRaising,
			},
		},
	},

	"ws": {
		"/alive": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/ready": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/ws": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v2/ws": {
			"GET": {
				types.ScopePublic,
			},
		},
	},

	"api-admin": {
		"/alive": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/ready": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/admin/tags": {
			"GET": {
				types.ScopeAdminUserInfoRead,
			},
		},
		"/v1/admin/system/messages": {
			"GET": {
				types.ScopeAdminSystemMessageAdministration,
			},
			"POST": {
				types.ScopeAdminSystemMessageAdministration,
			},
		},
		"/v1/admin/system/messages/:message_id": {
			"GET": {
				types.ScopeAdminSystemMessageAdministration,
			},
			"PUT": {
				types.ScopeAdminSystemMessageAdministration,
			},
			"DELETE": {
				types.ScopeAdminSystemMessageAdministration,
			},
		},
		"/v1/admin/system/push_notification": {
			"GET": {
				types.ScopeAdminSystemPushAdministration,
			},
			"POST": {
				types.ScopeAdminSystemPushAdministration,
			},
		},
		"/v1/admin/system/version": {
			"GET": {
				types.ScopePublic,
			},
			"PUT": {
				types.ScopeAdminSystemVersionAdministration,
			},
		},
		"/v1/admin/system/emails": {
			"POST": {
				types.ScopeAdminSystemMessageAdministration,
			},
		},
		"/v1/admin/system/email/templates": {
			"GET": {
				types.ScopeAdminSystemMessageAdministration,
			},
		},
		"/v1/admin/system/email/templates/:template_id": {
			"GET": {
				types.ScopeAdminSystemMessageAdministration,
			},
			"POST": {
				types.ScopeAdminSystemMessageAdministration,
			},
		},
		"/v1/admin/system/feature_tables": {
			"POST": {
				types.ScopeAdminSystemFeatureTableAdministration,
			},
			"GET": {
				types.ScopeAdminSystemFeatureTableAdministration,
			},
		},
		"/v1/admin/system/feature_tables/:feature_table_id": {
			"GET": {
				types.ScopeAdminSystemFeatureTableAdministration,
			},
			"PUT": {
				types.ScopeAdminSystemFeatureTableAdministration,
			},
			"DELETE": {
				types.ScopeAdminSystemFeatureTableAdministration,
			},
		},
		"/v1/admin/system/cob_point_constants": {
			"GET": {
				types.ScopeAdminSystemCOBPointConstantsAdministration,
			},
			"PUT": {
				types.ScopeAdminSystemCOBPointConstantsAdministration,
			},
		},
		"/v1/admin/roles/auditors": {
			"GET": {
				types.ScopeAdminGrantKYCAuditor,
			},
			"POST": {
				types.ScopeAdminGrantKYCAuditor,
			},
		},
		"/v1/admin/roles/auditors/:user_id": {
			"DELETE": {
				types.ScopeAdminGrantKYCAuditor,
			},
		},
		"/v1/admin/roles/developers": {
			"GET": {
				types.ScopeAdminGrantDeveloper,
			},
			"POST": {
				types.ScopeAdminGrantDeveloper,
			},
		},
		"/v1/admin/roles/developers/:user_id": {
			"DELETE": {
				types.ScopeAdminGrantDeveloper,
			},
		},
		"/v1/admin/roles/pr_members": {
			"GET": {
				types.ScopeAdminGrantPRMember,
			},
			"POST": {
				types.ScopeAdminGrantPRMember,
			},
		},
		"/v1/admin/roles/pr_members/:user_id": {
			"DELETE": {
				types.ScopeAdminGrantPRMember,
			},
		},
		"/v1/admin/roles/cs_members": {
			"GET": {
				types.ScopeAdminGrantCSMember,
			},
			"POST": {
				types.ScopeAdminGrantCSMember,
			},
		},
		"/v1/admin/roles/cs_members/:user_id": {
			"DELETE": {
				types.ScopeAdminGrantCSMember,
			},
		},
		"/v1/admin/roles/coin_offering_managers": {
			"GET": {
				types.ScopeAuditCommitteeSuperAdmin,
			},
		},
		"/v1/admin/roles/financial_product_managers": {
			"GET": {
				types.ScopeAuditCommitteeSuperAdmin,
			},
		},
		"/v1/admin/roles/cs_managers": {
			"GET": {
				types.ScopeAuditCommitteeSuperAdmin,
			},
		},
		"/v1/admin/roles/release_managers": {
			"GET": {
				types.ScopeAuditCommitteeSuperAdmin,
			},
		},
		"/v1/admin/roles/developer_managers": {
			"GET": {
				types.ScopeAuditCommitteeSuperAdmin,
			},
		},
		"/v1/admin/roles/balance_managers": {
			"GET": {
				types.ScopeAuditCommitteeSuperAdmin,
			},
		},
		"/v1/admin/roles/pr_managers": {
			"GET": {
				types.ScopeAuditCommitteeSuperAdmin,
			},
		},
		"/v1/admin/roles/mkt_managers": {
			"GET": {
				types.ScopeAuditCommitteeSuperAdmin,
			},
		},
		"/v1/admin/committee/motions": {
			"GET": {
				types.ScopeAuditCommitteeSuperAdmin,
			},
			"POST": {
				types.ScopeAuditCommitteeSuperAdmin,
			},
		},
		"/v1/admin/committee/motions/:motion_id": {
			"PUT": {
				types.ScopeAuditCommitteeSuperAdmin,
			},
		},
		"/v1/admin/coin_info/currencies": {
			"GET": {
				types.ScopeAdminCoinInfoRead,
			},
		},
		"/v1/admin/coin_info/currencies/:currency_id": {
			"PATCH": {
				types.ScopeAdminCoinInfoWrite,
			},
			"POST": {
				types.ScopeAdminCoinInfoWrite,
			},
		},
		"/v1/admin/coin_info/coin_sources": {
			"GET": {
				types.ScopeAdminCoinInfoRead,
			},
		},
		"/v1/admin/coin_info/coin_source": {
			"PATCH": {
				types.ScopeAdminCoinInfoWrite,
			},
			"POST": {
				types.ScopeAdminCoinInfoWrite,
			},
		},
		"/v1/admin/coin_info/trading_pairs": {
			"GET": {
				types.ScopeAdminCoinInfoRead,
			},
		},
		"/v1/admin/coin_info/trading_pairs/:trading_pair_id": {
			"PATCH": {
				types.ScopeAdminCoinInfoWrite,
			},
			"POST": {
				types.ScopeAdminCoinInfoWrite,
			},
		},
		"/v1/blockchain_sanitizer/execute_sanitizer": {
			"POST": {
				types.ScopeAdminGrantDeveloper,
			},
		},
		"/v1/account/device": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/register": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/resend_email_verification": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/confirm_email_verification": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/check_email_verification": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/login": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/check_eosio_account_duplicated": {
			"GET": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/account/get_eos_required_amount": {
			"GET": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/account/create_eos_account": {
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/account/confirm_device_verification": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/check_device_verification": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/resend_device_verification": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/forgot_password": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/reset_password": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/change_password": {
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/account/enable_two_factor_authentication": {
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/account/verify_two_factor_authentication": {
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/account/disable_two_factor_authentication": {
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/account/change_email": {
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/account/confirm_change_email": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/delete_account": {
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/account/confirm_delete_account": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/ephemeral_picture": {
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/account/confirm_enable_two_factor_authentication": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/confirm_disable_two_factor_authentication": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/confirm_two_factor_authentication": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/refresh_token": {
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/account/device_authorizations": {
			"GET": {
				types.ScopeExchangeAccountRead,
			},
		},
		"/v1/account/device_authorizations/:device_authorization_id": {
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/account/disable_two_factor_authentication_picture": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/request_disable_two_factor_authentication": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/confirm_request_disable_two_factor_authentication": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/market/currencies": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/quote_currencies": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/get_all_currency_intro": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/currency_intro/:currency_id": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/trading_pairs": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/stats": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/trades/:trading_pair_id": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/trades_history/:trading_pair_id": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/orderbooks/:trading_pair_id": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/orderbook/precisions/:trading_pair_id": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/fundingbooks/:currency_id": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/fundingbook/precisions/:currency_id": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/tickers": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/tickers/:trading_pair_id": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/loan_tickers": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/loan_tickers/:currency_id": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/exchange_rates/:currency_id": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/explorers": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/info": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/campaign/get_all_end_point": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/gdpr_audit/ephemeral_picture": {
			"POST": {
				types.ScopeAdminUserInfoWrite,
			},
		},
		"/v1/gdpr_audit/change_email": {
			"GET": {
				types.ScopeAdminUserInfoRead,
			},
			"POST": {
				types.ScopeAdminUserInfoWrite,
			},
		},
		"/v1/gdpr_audit/delete_account": {
			"GET": {
				types.ScopeAdminUserInfoRead,
			},
		},
		"/v1/gdpr_audit/gdprs/:gpdr_id": {
			"GET": {
				types.ScopeAdminUserInfoRead,
			},
			"PUT": {
				types.ScopeAdminUserInfoWrite,
			},
		},
		"/v1/gdpr_audit/gdprs/:gdpr_id/pictures/:picture_id": {
			"GET": {
				types.ScopeAdminUserInfoRead,
			},
		},
		"/v1/kyc_audit/ephemeral_picture": {
			"POST": {
				types.ScopeExchangeKYCWrite,
			},
		},
		"/v1/kyc_audit/amls/:status": {
			"GET": {
				types.ScopeAdminKYCRead,
			},
		},
		"/v1/kyc_audit/aml/:aml_id": {
			"GET": {
				types.ScopeAdminKYCRead,
			},
			"PUT": {
				types.ScopeAdminLowRiskKYCApproval,
				types.ScopeAuditCommitteeKYCAuditor,
				types.ScopeAuditCommitteeKYCManager,
			},
		},
		"/v1/kyc_audit/aml/:aml_id/check": {
			"PUT": {
				types.ScopeAdminLowRiskKYCApproval,
				types.ScopeAuditCommitteeKYCAuditor,
				types.ScopeAuditCommitteeKYCManager,
			},
		},
		"/v1/kyc_audit/aml/:aml_id/investigate": {
			"PUT": {
				types.ScopeAdminLowRiskKYCApproval,
				types.ScopeAuditCommitteeKYCAuditor,
				types.ScopeAuditCommitteeKYCManager,
			},
		},
		"/v1/kyc_audit/aml/:aml_id/pictures/:picture_id": {
			"GET": {
				types.ScopeAdminKYCRead,
			},
		},
		"/v1/kyc_audit/kycs": {
			"GET": {
				types.ScopeAdminKYCRead,
			},
		},
		"/v1/kyc_audit/kycs/:kyc_id": {
			"GET": {
				types.ScopeAdminKYCRead,
			},
			"PUT": {
				types.ScopeAdminLowRiskKYCApproval,
				types.ScopeAuditCommitteeKYCAuditor,
				types.ScopeAuditCommitteeKYCManager,
			},
		},
		"/v1/kyc_audit/kycs/:kyc_id/aml": {
			"GET": {
				types.ScopeAdminKYCRead,
			},
		},
		"/v1/kyc_audit/kycs/:kyc_id/pictures/:picture_id": {
			"GET": {
				types.ScopeAdminKYCRead,
			},
		},
		"/v1/kyc_audit/kycs/:kyc_id/revoke/:target_level": {
			"POST": {
				types.ScopeAdminLowRiskKYCApproval,
				types.ScopeAuditCommitteeKYCAuditor,
				types.ScopeAuditCommitteeKYCManager,
			},
		},
		"/v1/funds/fiat/payment_methods/:payment_method_id": {
			"PATCH": {
				types.ScopeAuditCommitteeBalanceManager,
			},
		},
		"/v1/funds/crypto/scan_ethereum_multisig_tx/:tx_hash": {
			"POST": {
				types.ScopeAdminScanEthereumMultiSigTransaction,
			},
		},
		"/v1/funds/generic/deposits": {
			"GET": {
				types.ScopeAuditCommitteeBalanceManager,
			},
			"POST": {
				types.ScopeAdminUserInfoWrite,
			},
		},
		"/v1/funds/generic/deposits/:deposit_id": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/funds/generic/manual/deposits/:deposit_id": {
			"PUT": {
				types.ScopeAuditCommitteeBalanceManager,
			},
		},
		"/v1/funds/generic/manual/withdrawals/:withdrawal_id": {
			"PUT": {
				types.ScopeAuditCommitteeBalanceManager,
			},
		},
		"/v1/funds/generic/withdrawals/:withdrawal_id": {
			"PUT": {
				types.ScopeAuditCommitteeBalanceManager,
			},
		},
		"/v1/funds/generic/withdrawals": {
			"GET": {
				types.ScopeAdminUserLedgerRead,
			},
			"POST": {
				types.ScopeAdminUserInfoWrite,
			},
		},
		"/v1/funds/balances/move": {
			"POST": {
				types.ScopeAuditCommitteeBalanceManager,
			},
		},
		"/v1/funds/balances/move_all": {
			"POST": {
				types.ScopeAuditCommitteeBalanceManager,
			},
		},
		"/v1/funds/fiat/exchange_rate_factors": {
			"GET": {
				types.ScopeAuditCommitteeBalanceManager,
			},
		},
		"/v1/funds/fiat/exchange_rate_factors/:currency_id": {
			"GET": {
				types.ScopeAuditCommitteeBalanceManager,
			},
			"PUT": {
				types.ScopeAuditCommitteeBalanceManager,
			},
		},
		"/v1/crm/clients": {
			"GET": {
				types.ScopeAdminUserInfoRead,
			},
		},
		"/v1/crm/suspicion/records": {
			"GET": {
				types.ScopeAdminUserInfoRead,
			},
		},
		"/v1/crm/suspicion/records/:record_id": {
			"GET": {
				types.ScopeAdminUserInfoRead,
			},
			"PUT": {
				types.ScopeAdminUserInfoWrite,
			},
		},
		"/v1/crm/suspicion/file": {
			"POST": {
				types.ScopeAdminUserInfoWrite,
			},
		},
		"/v1/crm/suspicion/file/:file_id": {
			"GET": {
				types.ScopeAdminUserInfoRead,
			},
		},
		"/v1/crm/suspicion/rules": {
			"GET": {
				types.ScopeAdminUserInfoRead,
			},
		},
		"/v1/crm/suspicion/rules/:rule/:key": {
			"GET": {
				types.ScopeAdminUserInfoRead,
			},
			"PUT": {
				types.ScopeAdminUserInfoWrite,
			},
		},
		"/v1/crm/wallets": {
			"GET": {
				types.ScopeAdminUserInfoRead,
			},
		},
		"/v1/crm/get_clients": {
			"POST": {
				types.ScopeAdminUserInfoRead,
			},
		},
		"/v1/crm/clients/:client_id": {
			"GET": {
				types.ScopeAdminUserInfoRead,
			},
		},
		"/v1/crm/clients/:client_id/balances": {
			"GET": {
				types.ScopeAdminUserLedgerRead,
			},
		},
		"/v1/crm/clients/:client_id/funds_limit": {
			"GET": {
				types.ScopeAdminUserFundsLimitRead,
			},
			"PUT": {
				types.ScopeAdminUserFundsLimitWrite,
			},
		},
		"/v1/crm/clients/:client_id/slot_machine_tokens": {
			"GET": {
				types.ScopeAdminUserSlotMachineTokenRead,
			},
			"POST": {
				types.ScopeAdminUserSlotMachineTokenWrite,
			},
		},
		"/v1/crm/clients/:client_id/generic_withdrawals": {
			"GET": {
				types.ScopeAdminUserLedgerRead,
			},
		},
		"/v1/crm/clients/:client_id/generic_deposits": {
			"GET": {
				types.ScopeAdminUserLedgerRead,
			},
		},
		"/v1/crm/clients/:client_id/crypto_withdrawals": {
			"GET": {
				types.ScopeAdminUserLedgerRead,
			},
		},
		"/v1/crm/clients/:client_id/crypto_deposits": {
			"GET": {
				types.ScopeAdminUserLedgerRead,
			},
		},
		"/v1/crm/clients/:client_id/crypto_wallets": {
			"GET": {
				types.ScopeAdminUserLedgerRead,
			},
		},
		"/v1/crm/clients/:client_id/ledgers": {
			"GET": {
				types.ScopeAdminUserLedgerRead,
			},
		},
		"/v1/crm/clients/:client_id/orders": {
			"GET": {
				types.ScopeAdminUserLedgerRead,
			},
		},
		"/v1/crm/clients/:client_id/fundings": {
			"GET": {
				types.ScopeAdminUserLedgerRead,
			},
		},
		"/v1/crm/clients/:client_id/broker_orders": {
			"GET": {
				types.ScopeAdminUserLedgerRead,
			},
		},
		"/v1/crm/clients/:client_id/trades": {
			"GET": {
				types.ScopeAdminUserLedgerRead,
			},
		},
		"/v1/crm/clients/:client_id/orders/:order_id/trades": {
			"GET": {
				types.ScopeAdminUserLedgerRead,
			},
		},
		"/v1/crm/clients/:client_id/disable_two_factor_authentication": {
			"POST": {
				types.ScopeAdminUserInfoWrite,
			},
		},
		"/v1/crm/clients/:client_id/disable_user": {
			"PUT": {
				types.ScopeAdminUserAccountDisable,
			},
		},
		"/v1/crm/clients/:client_id/tags": {
			"GET": {
				types.ScopeAdminUserInfoRead,
			},
			"POST": {
				types.ScopeAdminUserInfoWrite,
			},
			"DELETE": {
				types.ScopeAdminUserInfoWrite,
			},
		},
		"/v1/crm/clients/:client_id/groups": {
			"GET": {
				types.ScopeAdminUserInfoRead,
			},
			"POST": {
				types.ScopeAdminUserInfoWrite,
			},
			"DELETE": {
				types.ScopeAdminUserInfoWrite,
			},
		},
		"/v1/crm/clients/:client_id/cob_points": {
			"GET": {
				types.ScopeAdminUserInfoRead,
			},
			"PUT": {
				types.ScopeAdminSystemCOBPointConstantsAdministration,
			},
		},
		"/v1/crm/clients/:client_id/cob_point_ledgers": {
			"GET": {
				types.ScopeAdminUserInfoRead,
			},
		},
		"/v1/crm/clients/:client_id/spg_ins": {
			"GET": {
				types.ScopeAdminUserLedgerRead,
			},
		},
		"/v1/campaign/events/:campaign_name/:component_name": {
			"GET": {
				types.ScopeAdminCampaignRead,
			},
			"POST": {
				types.ScopeAdminCampaignWrite,
			},
			"DELETE": {
				types.ScopeAdminCampaignWrite,
			},
		},
		"/v1/campaign/event_periods/:campaign_name/:component_name": {
			"POST": {
				types.ScopeAdminCampaignWrite,
			},
		},
		"/v1/campaign/manual_review_submit/:event_name/:submit_id/:picture_id": {
			"GET": {
				types.ScopeAdminCampaignRead,
			},
		},
		"/v1/reward/batch_transfer_motion": {
			"POST": {
				types.ScopeExchangeCryptoWithdrawal,
			},
		},
		"/v1/reward/batch_transfer_motions": {
			"GET": {
				types.ScopeAuditCommitteeBalanceManager,
			},
		},
		"/v1/reward/batch_transfer_motion/:motion_id": {
			"PUT": {
				types.ScopeAuditCommitteeBalanceManager,
			},
		},
		"/v1/campaign/promo_code": {
			"GET": {
				types.ScopeAdminCampaignRead,
			},
		},
		"/v1/campaign/promo_code/events": {
			"GET": {
				types.ScopeAdminCampaignRead,
			},
			"POST": {
				types.ScopeAdminCampaignWrite,
			},
		},
		"/v1/campaign/promo_code/events/:event": {
			"GET": {
				types.ScopeAdminCampaignRead,
			},
			"DELETE": {
				types.ScopeAdminCampaignWrite,
			},
		},
		"/v1/campaign/shop/items": {
			"POST": {
				types.ScopeAdminCampaignWrite,
			},
		},
		"/v1/campaign/shop/items/:item_id": {
			"DELETE": {
				types.ScopeAdminCampaignWrite,
			},
		},
		"/v1/2fa/requests": {
			"GET": {
				types.ScopeAdminUserInfoRead,
			},
		},
		"/v1/2fa/requests/:request_user_id": {
			"GET": {
				types.ScopeAdminUserInfoRead,
			},
		},
		"/v1/2fa/requests/:request_to_disable_two_fa_id": {
			"POST": {
				types.ScopeAdminUserInfoWrite,
			},
		},
		"/v1/2fa/vote/:request_to_disable_two_fa_id": {
			"POST": {
				types.ScopeAdminUserInfoWrite,
			},
		},
		"/v1/2fa/pictures/:picture_id": {
			"GET": {
				types.ScopeAdminUserInfoWrite,
			},
		},
		"/v1/funds_raising/financial_products": {
			"GET": {
				types.ScopePublic,
			},
			"POST": {
				types.ScopeAdminFinancialProductWrite,
			},
		},
		"/v1/funds_raising/closed_financial_products": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/funds_raising/financial_products/:id": {
			"GET": {
				types.ScopePublic,
			},
			"PUT": {
				types.ScopeAdminFinancialProductWrite,
			},
			"DELETE": {
				types.ScopeAdminFinancialProductWrite,
			},
		},
		"/v1/funds_raising/financial_products/:id/fake_invest": {
			"POST": {
				types.ScopeAdminFinancialProductWrite,
			},
		},
		"/v1/funds_raising/coin_offerings": {
			"GET": {
				types.ScopePublic,
			},
			"POST": {
				types.ScopeAdminCoinOfferingWrite,
			},
		},
		"/v1/funds_raising/coin_offerings/:id": {
			"GET": {
				types.ScopePublic,
			},
			"PUT": {
				types.ScopeAdminCoinOfferingWrite,
			},
			"DELETE": {
				types.ScopeAdminCoinOfferingWrite,
			},
		},
		"/v1/funds_raising/coin_offerings/:id/fake_invest": {
			"POST": {
				types.ScopeAdminCoinOfferingWrite,
			},
		},
		"/v1/fiat/spg/refunds/propose": {
			"POST": {
				types.ScopeAdminFiatRefundPropose,
				types.ScopeAdminFiatRefundApproval,
			},
		},
		"/v1/fiat/spg/refunds/vote/:motion_id": {
			"PUT": {
				types.ScopeAdminFiatRefundApproval,
			},
		},
		"/v1/fiat/spg/refunds": {
			"GET": {
				types.ScopeAdminFiatRefundPropose,
				types.ScopeAdminFiatRefundApproval,
			},
		},
	},

	"api-coblet": {
		"/alive": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/ready": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/system/version": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/system/time": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/system/info": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/system/messages": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/system/messages/:message_id": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/account/device": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/register": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/resend_email_verification": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/confirm_email_verification": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/check_email_verification": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/login": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/confirm_device_verification": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/check_device_verification": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/resend_device_verification": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/forgot_password": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/reset_password": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/change_password": {
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/account/enable_two_factor_authentication": {
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/account/verify_two_factor_authentication": {
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/account/confirm_enable_two_factor_authentication": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/disable_two_factor_authentication": {
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/account/confirm_disable_two_factor_authentication": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/change_email": {
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/account/confirm_change_email": {
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/account/delete_account": {
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/account/confirm_delete_account": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/ephemeral_picture": {
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/account/confirm_two_factor_authentication": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/refresh_token": {
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/account/device_authorizations": {
			"GET": {
				types.ScopeExchangeAccountRead,
			},
		},
		"/v1/account/device_authorizations/:device_authorization_id": {
			"POST": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/account/disable_two_factor_authentication_picture": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/request_disable_two_factor_authentication": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/account/confirm_request_disable_two_factor_authentication": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/user/info": {
			"GET": {
				types.ScopeExchangeAccountRead,
			},
		},
		"/v1/user/vip_info": {
			"GET": {
				types.ScopeExchangeAccountRead,
			},
		},
		"/v1/user/preferences": {
			"GET": {
				types.ScopeExchangeAccountRead,
			},
			"PUT": {
				types.ScopeExchangeAccountWrite,
			},
		},
		"/v1/market/currencies": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/quote_currencies": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/get_all_currency_intro": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/currency_intro/:currency_id": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/trading_pairs": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/stats": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/trades/:trading_pair_id": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/orderbooks/:trading_pair_id": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/orderbook/precisions/:trading_pair_id": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/tickers": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/tickers/:trading_pair_id": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/exchange_rates/:currency_id": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/explorers": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/fiat_exchange_rates": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/market/fiat_exchange_rates/:currency_id": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/kyc/id_types": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/kyc/tiers": {
			"GET": {
				types.ScopeExchangeKYCRead,
			},
		},
		"/v1/kyc/tiers/:tier_level": {
			"GET": {
				types.ScopeExchangeKYCRead,
			},
			"PUT": {
				types.ScopeExchangeKYCWrite,
			},
		},
		"/v1/kyc/phone_number": {
			"POST": {
				types.ScopeExchangeKYCWrite,
			},
		},
		"/v1/kyc/ephemeral_picture": {
			"POST": {
				types.ScopeExchangeKYCWrite,
			},
		},
		"/v1/kyc/pictures/:picture_id": {
			"GET": {
				types.ScopeExchangeKYCRead,
			},
		},
		"/v1/wallet/balances": {
			"GET": {
				types.ScopeExchangeLedgerRead,
			},
		},
		"/v1/wallet/withdrawal_frozen": {
			"GET": {
				types.ScopeExchangeCryptoWithdrawal,
			},
		},
		"/v1/wallet/withdrawals/:withdrawal_id": {
			"GET": {
				types.ScopeExchangeLedgerRead,
			},
			"DELETE": {
				types.ScopeExchangeCryptoWithdrawal,
			},
		},
		"/v1/wallet/withdrawals": {
			"GET": {
				types.ScopeExchangeLedgerRead,
			},
			"POST": {
				types.ScopeExchangeCryptoWithdrawal,
			},
		},
		"/v1/wallet/withdrawals/fee": {
			"POST": {
				types.ScopeExchangeCryptoWithdrawal,
			},
		},
		"/v1/wallet/limits/withdrawal": {
			"GET": {
				types.ScopeExchangeLedgerRead,
			},
		},
		"/v1/wallet/deposits/:deposit_id": {
			"GET": {
				types.ScopeExchangeLedgerRead,
			},
		},
		"/v1/wallet/deposits": {
			"GET": {
				types.ScopeExchangeLedgerRead,
			},
		},
		"/v1/wallet/ledger": {
			"GET": {
				types.ScopeExchangeLedgerRead,
			},
		},
		"/v1/wallet/transfer": {
			"POST": {
				types.ScopeExchangeWalletTransfer,
			},
		},
		"/v1/wallet/generic_deposits": {
			"GET": {
				types.ScopeExchangeLedgerRead,
			},
		},
		"/v1/wallet/generic_deposits/:generic_deposit_id": {
			"GET": {
				types.ScopeExchangeLedgerRead,
			},
		},
		"/v1/wallet/generic_withdrawals": {
			"GET": {
				types.ScopeExchangeLedgerRead,
			},
		},
		"/v1/wallet/generic_withdrawals/:generic_withdrawal_id": {
			"GET": {
				types.ScopeExchangeLedgerRead,
			},
			"DELETE": {
				types.ScopeExchangeCryptoWithdrawal,
			},
		},
		"/v1/wallet/deposit_addresses": {
			"GET": {
				types.ScopeExchangeLedgerRead,
			},
			"POST": {
				types.ScopeExchangeCryptoWithdrawal,
			},
		},
		"/v1/wallet/deposit_addresses/iota": {
			"GET": {
				types.ScopeExchangeCryptoWithdrawal,
			},
			"POST": {
				types.ScopeExchangeCryptoWithdrawal,
			},
		},
		"/v1/wallet/withdrawal_addresses": {
			"GET": {
				types.ScopeExchangeLedgerRead,
			},
			"POST": {
				types.ScopeExchangeCryptoWithdrawal,
			},
		},
		"/v1/wallet/withdrawal_addresses/:wallet_id": {
			"DELETE": {
				types.ScopeExchangeCryptoWithdrawal,
			},
		},
		"/v1/wallet/confirm_add_withdrawal_wallet": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/wallet/confirm_withdrawal": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/fiat/limits/:currency_id": {
			"GET": {
				types.ScopeExchangeLedgerRead,
			},
		},
		"/v1/fiat/deposits": {
			"GET": {
				types.ScopeExchangeFiatDeposit,
			},
		},
		"/v1/fiat/deposits/:deposits_id": {
			"GET": {
				types.ScopeExchangeFiatDeposit,
			},
		},
		"/v1/fiat/withdrawals": {
			"GET": {
				types.ScopeExchangeFiatWithdrawal,
			},
			"POST": {
				types.ScopeExchangeFiatWithdrawal,
			},
		},
		"/v1/fiat/confirm_withdrawals": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/fiat/withdrawals/:withdrawal_id": {
			"GET": {
				types.ScopeExchangeFiatWithdrawal,
			},
			"DELETE": {
				types.ScopeExchangeFiatWithdrawal,
			},
		},
		"/v1/chart/candles/:trading_pair_id": {
			"GET": {
				types.ScopePublic,
			},
		},
	},

	"test": {
		"/alive": {
			"GET": {
				types.ScopeAuditCommitteeKYCAuditor,
				types.ScopeAuditCommitteeSuperAdmin,
			},
		},
		"/ready": {
			"GET": {
				types.ScopeAuditCommitteeKYCAuditor,
				types.ScopeAuditCommitteeSuperAdmin,
			},
		},
		"/v1/helo": {
			"POST": {
				types.ScopeAuditCommitteeKYCAuditor,
				types.ScopeAuditCommitteeSuperAdmin,
			},
		},
		"/v1/users": {
			"GET": {
				types.ScopePublic,
			},
		},
		"/v1/users/:user_id": {
			"GET": {
				types.ScopeAuditCommitteeKYCAuditor,
				types.ScopeAuditCommitteeSuperAdmin,
				types.ScopeExchangeAccountRead,
			},
			"PUT": {
				types.ScopeAuditCommitteeKYCAuditor,
				types.ScopeAuditCommitteeSuperAdmin,
				types.ScopeExchangeAccountRead,
			},
		},
		"/v1/oauth2/token": {
			"POST": {
				types.ScopePublic,
			},
		},
		"/v1/oauth2/resources/userinfo": {
			"GET": {
				types.ScopeThirdPartyAccountRead,
			},
		},
		"/v1/oauth2/resources/kyc_tiers": {
			"GET": {
				types.ScopeThirdPartyKYCRead,
			},
		},
	},
}
